### PR TITLE
Fix logging and multi line alt texts

### LINKED ISSUE #3: No command recognized when message contains newline
**Example message:**
> !alt Test1
> Test2

**Current Result:**
Input message not deleted, no message from bot, no error within log.

**Expected Result:**
Standard functionality, with message including newline.

### LINKED ISSUE #4: Repeated logging prefixes
Issue where there are repeated log message prefixes each time a command is executed, 1 new one is added per execution.

### PR DESCRIPTION
**Pull request by Glossawy**
fixes #3 
fixes #4

### CODE REVIEW

File: src/main/java/com/zacharytalis/alttextbot/utils/Toolbox.java [hunk 1]
```diff
@@ -83,15 +83,25 @@ public static Logger getLogger(Class<?> clazz) {
...
-        classLoggers.put(clazz, logger);
-        return logger;
+
+        if (botLogger instanceof PrefixingLogger logger && logger.getPrefix().equals(prefix))
+            return logger;
+        else {
+            final var logger = new PrefixingLogger(botLogger, prefix);
+            classLoggers.put(clazz, logger);
+            return logger;
+        }
```
Comment (Glossawy) [inline src/main/java/com/zacharytalis/alttextbot/utils/Toolbox.java:105]: Not the most ideal, but works for now.
